### PR TITLE
Added ivim definitions to the eval help page.

### PR DESCRIPTION
**Pull request by drbarrett**
Documentation change to add entries to eval.txt for  has('ios'), has('gui_ios') and has('ivim')

### CODE REVIEW

**Comment by terrychou** [comment]
Please also update the updated date at the top of this document file.

**Comment by drbarrett** [comment]
Fixed the modified date to reflect the file has been changed.

**Comment by terrychou** [comment]
It is weird that the changed places suddenly became huge (+55-52).

**Comment by drbarrett** [comment]
Ugh, I didn’t look at the diff. It probably made tab/space changes. I'll fix it tomorrow

**Comment by drbarrett** [comment]
Well it still shows a lot of changes, but those are all from putting the file back to how it was. It might be cleaner from a history perspective to just drop the new file into your tree rather than take the pull.

**Pull request merged**
