### PR TITLE
Fix the Caps-Locks as CTRL setting

### PR DESCRIPTION
**Pull request by ghost**
fix: Track caps-lock state separately from alphaShift using new methods added in iOS 13.4.
note: I only have tested this on my iPad.

Although, iPadOS has support for mapping caps-lock on the native keyboard. iVim still has options to locally map the key. This uses the new iOS 13.4 methods to manually keep track of when the caps-lock key is being pressed and fakes alphaShift so that ctrl works again.

I tested
- the old Caps-Lock as "esc" and "none" settings to make sure they still work
- that caps-lock as ctrl works over several days of using iVim.

### CODE REVIEW

**Comment by voltprime-b** [comment]
For context,

I enjoy using caps-lock as both a control key and an escape key. Since iVim doesn't currently support it, I went ahead and made some commits to get that to work and have been playing with it for a week on my iPad. (iVim is an amazing app! Thank you so much for making this!)

I have another commit that'll actually add the option to map ctrl to esc on release:
  https://github.com/voltprime-b/iVim/commit/ef0eba805c731ae736cbea1f12ac7febcbc333d4
That is if ctrl (either physical or mapped by iVim/iOS) is pressed and released without any other keys pressed, it'll act as an escape key.

**Comment by terrychou** [comment]
The idea of mapping empty `ctrl` release to `esc` is great!

However, I have tested it on my iPad but it didn't work for me. I have applied the two commits from this PR but not https://github.com/voltprime-b/iVim/commit/ef0eba805c731ae736cbea1f12ac7febcbc333d4 . Should I apply the latter too to make it work? I will have more tests to see whether it was due to mistakes from my end.

On the other hand, the `caps lock` mapping to `ctrl` has been indeed fixed with this PR. However, since it only works above version 13.4, I don't think it has many use cases (because users would choose the system `caps lock` mapping over this).

My ideal situation is that, in systems above version 13.4, users choose the native `caps lock` mapping to `ctrl`, then we provide an option for them to choose to mapping `ctrl` release to `esc`. Paradise that would be ~~~

**Comment by voltprime-b** [comment]
Yes, https://github.com/voltprime-b/iVim/commit/ef0eba805c731ae736cbea1f12ac7febcbc333d4 has all the changes to make `ctrl` map to `esc`. Please apply that if you'd like to try it out. 

This PR only affects the current `caps lock` to `ctrl` mapping in iVim.

https://github.com/voltprime-b/iVim/commit/ef0eba805c731ae736cbea1f12ac7febcbc333d4 does allow combining the native `caps lock` to `ctrl` mapping with a setting in iVim to map `ctrl` release to `esc` too. Which sounds like the ideal situation you are looking for. 

Do you want the current `caps lock` settings to be removed from iVim?

**Comment by voltprime-b** [comment]
I could remove the current `caps lock` setting and replace it with the new `ctrl` mapped on release to `esc` setting in a new PR. Maybe even adding a note in the iVim's settings to let users know that they can go to iOS's keyboard settings to change what caps lock does.

Does that sound good to you?

**Comment by terrychou** [comment]
I have tried https://github.com/voltprime-b/iVim/commit/ef0eba805c731ae736cbea1f12ac7febcbc333d4 , and it worked great!

After reading the code, I have an idea.

It looks like you capture as many key commands as possible into `ctrlToEscOnRelease`. Is it possible that we only capture the key command for single `ctrl` key to make this work? My idea is:
1. record the single `ctrl` key pressing in `keyCommandTriggered`;
2. detect the key presses events only in `pressesBegan`, `pressesEnded` and `pressesCancelled`. In this case, we can even escape from the dependency on iOS 13.4;
3. of course, it needs special handling when the `ctrl` is from a `caps lock` mapping.

Do you think this would work? Would you like to give it a try?

**Comment by voltprime-b** [comment]
That sounds good; I'll give it a shot!

**Comment by voltprime-b** [comment]
I created a new PR with the feature to map ctrl-to-esc on release.

It now only watches the `ctrl` key inside of `keyCommandTriggered`. And tracks the other keys with the new iOS 13.4 functions (`pressesBegan`, `pressesEnded`, and `pressesCancelled`). 

Though, I'm confused by what you mean by "we can even escape from the dependency on iOS 13.4". I believe the new `pressesXXX` functions were introduced in iOS 13.4, so it still needs iOS 13.4 to make the ctrl-to-esc-on-release and caps-lock-to-ctrl mappings work.

**Comment by voltprime-b** [comment]
Since the "ctrl-to-esc on release" feature is now conditioned on iOS 13.4. This fix could be implemented using that logic, so I rebased this code onto that PR and reintroduced a fix in case the user tries to use iVim's settings to map caps-lock to ctrl.

**Comment by terrychou** [comment]
Because this fix only works above iOS 13.4 and systems satisfying this requirement provide native `caps lock` key mapping, I will not merge it for now. But I will leave it here in case of any possible changes in the future.

**Review by jserranoq — APPROVED** [review]

**Review by imanoobtocode — APPROVED** [review]

**Pull request closed without merging**
