### PR TITLE
Added support for has('ios') checking in scripts.

### PR DESCRIPTION
**Pull request by drbarrett**
Tiny change to allow scripts to call has('ios') to check if they are running under iVim on IOS. 

MacVim uses 'gui_macvim' and nvim uses 'nvim' so a more specific term rather than 'ios' might be better.

### CODE REVIEW

**Comment by terrychou** [comment]
This is a good one, since it was mentioned in issue #11 and solved by a workaround then.
I would like to make the name more specific though. Like how other vim variants do as you mentioned, 'ivim' would be a better choice. After all, iVim can only take responsibility for this name rather than 'ios'. How do you say?

**Comment by drbarrett** [comment]
ivim is probably better since you have specific commands added. I originally picked ios because it could be used for the larger limitations on ios like no forking. Any other vim port would have those same issues.

Maybe add both? Otherwise, either is fine with me I just want to be able to manage one set of vim config files everywhere.

**Comment by terrychou** [comment]
Yes, adding both will do. Would you please make the modification? Then I can merge this request into the master branch.

**Comment by drbarrett** [comment]
I've looked at some other vim forks, and based on that decided to add a 3rd test.
The following will all return true:
has('ivim')
has('ios')
has('gui_ios')

**Pull request merged**
